name: Deployment

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > key.pem
          chmod 400 key.pem

      - name: SSH into EC2, clone repo, and deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -tt ubuntu@${{ secrets.S_IP }} << 'EOF'
            sudo rm -rf /var/www/picstore
            git clone https://${{ secrets.GH_PAT }}@github.com/surendrakumar6350/picstore.git /var/www/picstore
            sudo chown -R www-data:www-data /var/www/picstore
            sudo chmod -R 755 /var/www/picstore
            sudo systemctl restart apache2
            echo "✅ PHP app deployed successfully"
            exit 0
          EOF